# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowChooseGame.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WindowChooseGame(object):
    def setupUiChooseGame(self, WindowChooseGame):
        WindowChooseGame.setObjectName("WindowChooseGame")
        WindowChooseGame.resize(700, 400)
        self.centralwidget = QtWidgets.QWidget(WindowChooseGame)
        self.centralwidget.setObjectName("centralwidget")
        self.xo_button = QtWidgets.QPushButton(self.centralwidget)
        self.xo_button.setGeometry(QtCore.QRect(265, 320, 180, 40))
        self.xo_button.setObjectName("xo_button")
        self.exit_profile_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_profile_button.setGeometry(QtCore.QRect(509, 330, 171, 23))
        self.exit_profile_button.setObjectName("exit_profile_button")
        self.label_choose_game = QtWidgets.QLabel(self.centralwidget)
        self.label_choose_game.setGeometry(QtCore.QRect(265, 0, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_choose_game.setFont(font)
        self.label_choose_game.setObjectName("label_choose_game")
        self.xo_image = QtWidgets.QLabel(self.centralwidget)
        self.xo_image.setGeometry(QtCore.QRect(200, 30, 301, 301))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.xo_image.setFont(font)
        self.show_rating_of_games = QtWidgets.QPushButton(self.centralwidget)
        self.show_rating_of_games.setGeometry(QtCore.QRect(20, 330, 171, 23))
        self.show_rating_of_games.setObjectName("show_rating_of_games")
        WindowChooseGame.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WindowChooseGame)
        self.menubar.setGeometry(QtCore.QRect(400, 400, 374, 40))
        self.menubar.setObjectName("menubar")
        WindowChooseGame.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WindowChooseGame)
        self.statusbar.setObjectName("statusbar")
        WindowChooseGame.setStatusBar(self.statusbar)

        self.pixmap = QtGui.QPixmap('photo.jpg')
        self.xo_image.setPixmap(self.pixmap)

        QtCore.QMetaObject.connectSlotsByName(WindowChooseGame)
        _translate = QtCore.QCoreApplication.translate
        WindowChooseGame.setWindowTitle(_translate("WindowChooseGame", "Tic Tac Toe"))
        self.xo_button.setText(_translate("WindowChooseGame", "Начать игру!"))
        self.exit_profile_button.setText(_translate("WindowChooseGame", "Выход"))
        self.label_choose_game.setText(_translate("WindowChooseGame", "Tic Tac Toe"))
        self.show_rating_of_games.setText(_translate("WindowChooseGame", "Ваш рейтинг"))
