# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowNewAccount.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowNewAccount(object):
    def setupUiNewAccount(self, MainWindowNewAccount):
        MainWindowNewAccount.setObjectName("MainWindowNewAccount")
        MainWindowNewAccount.resize(331, 214)
        self.centralwidget = QtWidgets.QWidget(MainWindowNewAccount)
        self.centralwidget.setObjectName("centralwidget")
        self.password = QtWidgets.QLabel(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(10, 60, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.log_in = QtWidgets.QLabel(self.centralwidget)
        self.log_in.setGeometry(QtCore.QRect(20, 20, 57, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.log_in.setFont(font)
        self.log_in.setObjectName("log_in")
        self.label_of_error = QtWidgets.QLabel(self.centralwidget)
        self.label_of_error.setGeometry(QtCore.QRect(10, 90, 311, 16))
        self.label_of_error.setText("")
        self.label_of_error.setObjectName("label_of_error")
        self.log_in_input = QtWidgets.QLineEdit(self.centralwidget)
        self.log_in_input.setGeometry(QtCore.QRect(80, 20, 241, 20))
        self.log_in_input.setObjectName("log_in_input")
        self.password_input = QtWidgets.QLineEdit(self.centralwidget)
        self.password_input.setGeometry(QtCore.QRect(80, 60, 241, 20))
        self.password_input.setObjectName("password_input")
        self.pushButton_ok = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ok.setGeometry(QtCore.QRect(240, 140, 80, 23))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.pushButton_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cancel.setGeometry(QtCore.QRect(150, 140, 80, 23))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        MainWindowNewAccount.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowNewAccount)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 331, 20))
        self.menubar.setObjectName("menubar")
        MainWindowNewAccount.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowNewAccount)
        self.statusbar.setObjectName("statusbar")
        MainWindowNewAccount.setStatusBar(self.statusbar)

        _translate = QtCore.QCoreApplication.translate
        MainWindowNewAccount.setWindowTitle(_translate("MainWindowNewAccount", "MainWindow"))
        self.password.setText(_translate("MainWindowNewAccount", "Пароль:"))
        self.log_in.setText(_translate("MainWindowNewAccount", "Логин:"))
        self.pushButton_ok.setText(_translate("MainWindowNewAccount", "ОК"))
        self.pushButton_cancel.setText(_translate("MainWindowNewAccount", "Отмена"))
        QtCore.QMetaObject.connectSlotsByName(MainWindowNewAccount)

