# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowRating.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowRating(object):
    def setupUiRating(self, MainWindowRating):
        MainWindowRating.setObjectName("MainWindowRating")
        MainWindowRating.resize(694, 255)
        self.centralwidget = QtWidgets.QWidget(MainWindowRating)
        self.centralwidget.setObjectName("centralwidget")
        self.table_of_rating = QtWidgets.QTableWidget(self.centralwidget)
        self.table_of_rating.setGeometry(QtCore.QRect(110, 70, 471, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.table_of_rating.setFont(font)
        self.table_of_rating.setObjectName("table_of_rating")
        self.table_of_rating.setColumnCount(3)
        self.table_of_rating.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_rating.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_rating.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_rating.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_rating.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_rating.setHorizontalHeaderItem(2, item)
        self.rating_label = QtWidgets.QLabel(self.centralwidget)
        self.rating_label.setGeometry(QtCore.QRect(90, 10, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rating_label.setFont(font)
        self.rating_label.setObjectName("rating_label")
        self.choose_profile = QtWidgets.QComboBox(self.centralwidget)
        self.choose_profile.setGeometry(QtCore.QRect(240, 10, 261, 23))
        self.choose_profile.setObjectName("choose_profile")
        self.back_to_menu_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_to_menu_button.setGeometry(QtCore.QRect(500, 170, 171, 23))
        self.back_to_menu_button.setObjectName("back_to_menu_button")
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_button.setGeometry(QtCore.QRect(510, 10, 80, 23))
        self.search_button.setObjectName("search_button")
        MainWindowRating.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowRating)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 694, 20))
        self.menubar.setObjectName("menubar")
        MainWindowRating.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowRating)
        self.statusbar.setObjectName("statusbar")
        MainWindowRating.setStatusBar(self.statusbar)

        QtCore.QMetaObject.connectSlotsByName(MainWindowRating)
        _translate = QtCore.QCoreApplication.translate
        MainWindowRating.setWindowTitle(_translate("MainWindowRating", "MainWindow"))
        item = self.table_of_rating.verticalHeaderItem(0)
        item.setText(_translate("MainWindowRating", "Крестики нолики"))
        item = self.table_of_rating.verticalHeaderItem(1)
        item.setText(_translate("MainWindowRating", "Всего игр"))
        item = self.table_of_rating.horizontalHeaderItem(1)
        item.setText(_translate("MainWindowRating", "Победы"))
        item = self.table_of_rating.horizontalHeaderItem(2)
        item.setText(_translate("MainWindowRating", "Поражения"))
        self.rating_label.setText(_translate("MainWindowRating", "Рейтинг игрока:"))
        self.back_to_menu_button.setText(_translate("MainWindowRating", "Вернуться к выбору игр"))
        self.search_button.setText(_translate("MainWindowRating", "Поиск"))
