# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowLogIn.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowLogIn(object):
    def setupUiLogIn(self, MainWindowLogIn):
        MainWindowLogIn.setObjectName("MainWindowLogIn")
        MainWindowLogIn.resize(365, 209)
        self.centralwidget = QtWidgets.QWidget(MainWindowLogIn)
        self.centralwidget.setObjectName("centralwidget")
        self.log_in = QtWidgets.QLabel(self.centralwidget)
        self.log_in.setGeometry(QtCore.QRect(30, 40, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.log_in.setFont(font)
        self.log_in.setObjectName("log_in")
        self.password = QtWidgets.QLabel(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(30, 80, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.log_in_input_login = QtWidgets.QLineEdit(self.centralwidget)
        self.log_in_input_login.setGeometry(QtCore.QRect(115, 40, 231, 21))
        self.log_in_input_login.setObjectName("log_in_input")
        self.password_input_login = QtWidgets.QLineEdit(self.centralwidget)
        self.password_input_login.setGeometry(QtCore.QRect(115, 80, 231, 21))
        self.password_input_login.setObjectName("password_input")
        self.label_of_error_login = QtWidgets.QLabel(self.centralwidget)
        self.label_of_error_login.setGeometry(QtCore.QRect(20, 100, 291, 16))
        self.label_of_error_login.setText("")
        self.label_of_error_login.setObjectName("label_of_error")
        self.pushButton_ok_login = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ok_login.setGeometry(QtCore.QRect(260, 140, 80, 23))
        self.pushButton_ok_login.setObjectName("pushButton_ok")
        self.pushButton_cancel_login = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cancel_login.setGeometry(QtCore.QRect(25, 140, 80, 23))
        self.pushButton_cancel_login.setObjectName("pushButton_cancel")
        MainWindowLogIn.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowLogIn)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 333, 20))
        self.menubar.setObjectName("menubar")
        MainWindowLogIn.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowLogIn)
        self.statusbar.setObjectName("statusbar")
        MainWindowLogIn.setStatusBar(self.statusbar)

        _translate = QtCore.QCoreApplication.translate
        MainWindowLogIn.setWindowTitle(_translate("MainWindowLogIn", "MainWindow"))
        self.log_in.setText(_translate("MainWindowLogIn", "Логин:"))
        self.password.setText(_translate("MainWindowLogIn", "Пароль:"))
        self.pushButton_ok_login.setText(_translate("MainWindowLogIn", "ОК"))
        self.pushButton_cancel_login.setText(_translate("MainWindowLogIn", "Отмена"))
        QtCore.QMetaObject.connectSlotsByName(MainWindowLogIn)

